import type { Metadata } from "next";

import "../styles/globals.css";
import AppWrapper from "@/components/AppWrapper";



export const metadata: Metadata = {
  title: "My App",
  description: "Generated by create next app",
  // viewport: "width=device-width, initial-scale=1, maximum-scale=1",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={""}>
        <AppWrapper> {children}</AppWrapper>
      </body>
    </html>
  );
}
